server:
  port: 9092

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: group-messages
          uri: http://localhost:9091/
          predicates:
            - Path=/group/**
        - id: user
          uri: http://localhost:9095/
          predicates:
            - Path=/user/**
        - id: Group-Member
          uri: http://localhost:9098/
          predicates:
            - Path=/groupMember/**
        - id: Message-Module
          uri: http://localhost:9081/
          predicates:
            - Path=/message/**
        - id: Group-Module
          uri: http://localhost:9082/
          predicates:
            - Path=/group/**
